'use client';
import React, { useEffect, useRef, useState } from 'react';
import { AlertTriangle, Bell, Briefcase, CheckCheck, ExternalLink, Flame, Info, RefreshCw, Trash2, X } from 'lucide-react';
const API = process.env.NEXT_PUBLIC_API_URL || (typeof window !== 'undefined' && !['localhost', '127.0.0.1'].includes(window.location.hostname) && window.location.protocol === 'https:' ? 'https://tracker-backend-rnec.onrender.com/api' : 'http://127.0.0.1:5000/api');
interface Notif { _id: string; type: string; title: string; body: string; url?: string; read: boolean; createdAt: string; }
const styles: Record<string, { label: string; icon: React.ReactNode }> = { job_alert: { label: 'Job alert', icon: <Briefcase size={15}/> }, streak_warning: { label: 'Streak', icon: <Flame size={15}/> }, dsa_reminder: { label: 'Reminder', icon: <AlertTriangle size={15}/> }, application_update: { label: 'Application', icon: <Briefcase size={15}/> }, system: { label: 'System', icon: <Info size={15}/> } };
const ago = (s: string) => { const m = Math.floor((Date.now() - new Date(s).getTime()) / 60000); return m < 1 ? 'Now' : m < 60 ? `${m}m` : m < 1440 ? `${Math.floor(m / 60)}h` : `${Math.floor(m / 1440)}d`; };
export default function NotificationBell() {
  const [open, setOpen] = useState(false), [items, setItems] = useState<Notif[]>([]), [unread, setUnread] = useState(0), [loading, setLoading] = useState(false); const panelRef = useRef<HTMLDivElement>(null);
  const fetchNotifs = async () => { try { const d = await (await fetch(`${API}/notifications`)).json(); if (d.success) { setItems(d.data || []); setUnread(d.unreadCount || 0); } } catch {} };
  useEffect(() => { fetchNotifs(); let es: EventSource | undefined; try { es = new EventSource(`${API}/notifications/stream`); es.onmessage = e => { try { const m = JSON.parse(e.data); if (m.type === 'init' || m.type === 'update') { setUnread(m.unreadCount || 0); if (m.latest) setItems(p => [m.latest, ...p.filter(n => n._id !== m.latest._id)]); } } catch {} }; } catch {} return () => es?.close(); }, []);
  const markRead = async () => { try { await fetch(`${API}/notifications/read-all`, { method: 'PUT' }); setItems(p => p.map(n => ({ ...n, read: true }))); setUnread(0); } catch {} };
  const clear = async () => { try { await fetch(`${API}/notifications`, { method: 'DELETE' }); setItems([]); setUnread(0); } catch {} };
  const trigger = async () => { setLoading(true); try { await fetch(`${API}/notifications/trigger`, { method: 'POST' }); await fetchNotifs(); } catch {} finally { setLoading(false); } };
  return <div className="notification-wrap" ref={panelRef}><button aria-label={`Notifications${unread ? `, ${unread} unread` : ''}`} aria-expanded={open} onClick={() => setOpen(v => !v)} className="notification-trigger"><Bell size={18}/>{unread > 0 && <b>{unread > 9 ? '9+' : unread}</b>}</button>{open && <div className="notification-panel" role="dialog" aria-label="Notifications"><header><div><span className="notification-eyebrow">INBOX</span><h3>Notifications</h3><p>{unread ? `${unread} waiting for you` : 'You are all caught up'}</p></div><div className="notification-head-actions">{unread > 0 && <button onClick={markRead} aria-label="Mark all notifications as read"><CheckCheck size={16}/></button>}<button onClick={() => setOpen(false)} aria-label="Close notifications"><X size={17}/></button></div></header><div className="notification-list">{items.length === 0 ? <div className="notification-empty"><div><Bell size={19}/></div><strong>Nothing new</strong><span>Fresh updates will appear here.</span></div> : items.map(n => { const s = styles[n.type] || styles.system; return <article className={`notification-item ${n.read ? '' : 'unread'}`} key={n._id}><div className="notification-icon">{s.icon}</div><div className="notification-copy"><div><strong>{n.title}</strong><time>{ago(n.createdAt)}</time></div><span className="notification-type">{s.label}</span><p>{n.body}</p>{n.url && <a href={n.url}>Open update <ExternalLink size={12}/></a>}</div></article>; })}</div><footer><button onClick={trigger} disabled={loading}><RefreshCw size={13} className={loading ? 'spin' : ''}/> Run checks</button>{items.length > 0 && <button onClick={clear} className="notification-clear"><Trash2 size={13}/> Clear</button>}</footer></div>}</div>;
}
